# Generated by Django 3.2.6 on 2021-11-11 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Имя Slug')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Отложенная публикация')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categoryarticle', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'новости',
                'ordering': ['-date_published'],
            },
        ),
    ]
