# Generated by Django 3.2.6 on 2021-08-19 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_published'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='categoryarticle',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
