# Generated by Django 3.2.6 on 2021-11-11 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=4, verbose_name='Номер кабинета')),
                ('type', models.CharField(choices=[('C', 'Кабинет'), ('A', 'Аудитория'), ('D', 'Дистанционно')], max_length=2, verbose_name='Тип кабинета')),
                ('building', models.IntegerField(default=1, verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'кабинет',
                'verbose_name_plural': 'кабинеты',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=64, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=64, verbose_name='Отчество')),
                ('position', models.CharField(blank=True, max_length=64, verbose_name='Должность')),
                ('contact', models.CharField(blank=True, max_length=256, verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'преподаватель',
                'verbose_name_plural': 'преподаватели',
            },
        ),
        migrations.CreateModel(
            name='TimeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, unique=True, verbose_name='Номер пары')),
                ('start_time', models.CharField(max_length=5, unique=True, verbose_name='Время начала')),
                ('end_time', models.CharField(max_length=5, unique=True, verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'время занятия',
                'verbose_name_plural': 'время занятий',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='Предмет')),
                ('lecturers', models.ManyToManyField(null=True, to='timetable.Lecturer', verbose_name='Преподаватели')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предметы',
            },
        ),
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_week', models.IntegerField(verbose_name='Номер недели')),
                ('start_week', models.IntegerField(blank=True, verbose_name='Начало недели')),
                ('end_week', models.IntegerField(blank=True, verbose_name='Конец недели')),
                ('cabinet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.classcabinet', verbose_name='Кабинет')),
                ('groups', models.ManyToManyField(to='auth.Group', verbose_name='Группы')),
                ('lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.lecturer', verbose_name='Преподаватель')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject', verbose_name='Предмет')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.timeschedule', verbose_name='Номер пары')),
            ],
            options={
                'verbose_name': 'занятие',
                'verbose_name_plural': 'занятия',
            },
        ),
    ]
