# Generated by Django 3.2.6 on 2021-12-23 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classcabinet',
            name='type',
        ),
    ]
