# Generated by Django 3.2.6 on 2021-12-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_remove_classcabinet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='lecturers',
        ),
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('UN', 'Неизвестно'), ('LE', 'Лек.'), ('PR', 'Пр.')], default='LE', max_length=2, verbose_name='Тип пары'),
        ),
    ]
