# Generated by Django 3.2.6 on 2021-11-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_subject_lecturers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonschedule',
            name='end_week',
            field=models.IntegerField(null=True, verbose_name='Конец недели'),
        ),
        migrations.AlterField(
            model_name='lessonschedule',
            name='start_week',
            field=models.IntegerField(null=True, verbose_name='Начало недели'),
        ),
    ]
