# Generated by Django 3.2.6 on 2021-11-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20211112_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonschedule',
            name='end_week',
            field=models.IntegerField(default=0, verbose_name='Конец недели'),
        ),
        migrations.AlterField(
            model_name='lessonschedule',
            name='start_week',
            field=models.IntegerField(default=0, verbose_name='Начало недели'),
        ),
    ]
