# Generated by Django 3.2.6 on 2021-11-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20211112_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonschedule',
            name='day_week',
            field=models.CharField(choices=[('MO', 'Понедельник'), ('TU', 'Вторник'), ('WE', 'Среда'), ('TH', 'Четверг'), ('FR', 'Пятница'), ('SA', 'Суббота'), ('SU', 'Воскресение')], default='SU', max_length=2, verbose_name='День недели'),
        ),
    ]
