# Generated by Django 3.2.6 on 2021-12-23 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('W', 'Ожидание публикации'), ('P', 'Опубликовано'), ('R', 'Отклонено'), ('C', 'Завершено')], default='W', max_length=2, verbose_name='Статус')),
                ('report', models.CharField(blank=True, max_length=256, verbose_name='Сообщение')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('votes', models.ManyToManyField(blank=True, related_name='event_votes', to=settings.AUTH_USER_MODEL, verbose_name='Проголосовавшие')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'мероприятия',
            },
        ),
    ]
